<script setup>
import { ref, computed, watch } from 'vue'
import { useAiGuidanceStore } from '../../stores/aiGuidanceStore'
import { useConfigStore } from '@/stores/configStore'
import { usePreferencesStore } from '@/stores/preferencesStore'
import AppletFrame from '../../components/AppletFrame.vue'
import {
  FileCheck,
  CheckCircle,
  Circle,
  ChevronDown,
  ChevronUp,
  Download,
  Info
} from 'lucide-vue-next'

const aiStore = useAiGuidanceStore()
const configStore = useConfigStore()
const preferencesStore = usePreferencesStore()

const APPLET_ID = 'clinical-validation'

// Load config from YAML
const appletConfig = computed(() => {
  return configStore.config?.clinicalGuidance?.['clinical-validation'] || {}
})

const sections = computed(() => appletConfig.value.sections || [])
const intro = computed(() => appletConfig.value.intro || {})

// Track checked items
const checkedItems = ref(new Set())

// Track expanded sections
const expandedSections = ref(new Set(['technical'])) // Start with first section expanded

function toggleSection(sectionId) {
  if (expandedSections.value.has(sectionId)) {
    expandedSections.value.delete(sectionId)
  } else {
    expandedSections.value.add(sectionId)
  }
}

function toggleItem(itemId) {
  if (checkedItems.value.has(itemId)) {
    checkedItems.value.delete(itemId)
  } else {
    checkedItems.value.add(itemId)
  }
}

// Compute progress
const allItems = computed(() => {
  return sections.value.flatMap(s => s.items || [])
})

const requiredItems = computed(() => {
  return allItems.value.filter(i => i.required)
})

const completedRequired = computed(() => {
  return requiredItems.value.filter(i => checkedItems.value.has(i.id))
})

const progress = computed(() => {
  const total = requiredItems.value.length
  const completed = completedRequired.value.length
  const percent = total > 0 ? Math.round((completed / total) * 100) : 0

  return {
    completed,
    total,
    percent,
    allComplete: completed === total
  }
})

const isComplete = computed(() => progress.value.allComplete)

// Save to store when checklist changes
watch([checkedItems, progress], () => {
  aiStore.completeApplet(APPLET_ID, {
    checkedItems: Array.from(checkedItems.value),
    progress: progress.value,
    completedAt: progress.value.allComplete ? new Date().toISOString() : null
  })
}, { deep: true })

// Download validation report
function downloadValidationReport() {
  const report = `# Clinical AI Validation Report

**Date:** ${new Date().toLocaleDateString()}
**Status:** ${progress.value.allComplete ? '✓ Ready for clinical deployment' : '⚠ Additional validation needed'}
**Progress:** ${progress.value.completed} / ${progress.value.total} required items (${progress.value.percent}%)

---

${sections.value.map(section => {
  return `## ${section.title}

${(section.items || []).map(item => {
    const checked = checkedItems.value.has(item.id)
    const req = item.required ? ' (Required)' : ' (Optional)'
    return `- [${checked ? 'x' : ' '}] ${item.text}${req}`
  }).join('\n')}
`
}).join('\n')}

---

${progress.value.allComplete ? `
## Summary

All required validation items completed. System is ready for:
- Clinical deployment review
- Publication in medical journals
- Regulatory submission (if applicable)
` : `
## Missing Required Items

The following items must be completed before deployment:

${requiredItems.value.filter(i => !checkedItems.value.has(i.id)).map(i => `- ${i.text}`).join('\n')}
`}

---

*Generated by OpenDataPlanner Clinical AI Guidance*
*This is a checklist tracker, not a substitute for formal validation documentation*
`

  const blob = new Blob([report], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `clinical-validation-report-${new Date().toISOString().slice(0, 10)}.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// Section progress
function getSectionProgress(section) {
  const sectionItems = section.items || []
  const required = sectionItems.filter(i => i.required)
  const completed = required.filter(i => checkedItems.value.has(i.id))
  return {
    completed: completed.length,
    total: required.length,
    percent: required.length > 0 ? Math.round((completed.length / required.length) * 100) : 0
  }
}
</script>

<template>
  <AppletFrame
    :applet-id="APPLET_ID"
    :title="appletConfig.meta?.title || 'Clinical Validation Checklist'"
    :core-question="appletConfig.meta?.core_question || 'Is my AI ready for clinical deployment?'"
    :icon="FileCheck"
    :is-complete="isComplete"
  >
    <!-- Intro -->
    <div
      v-if="intro.text"
      class="p-4 rounded-lg border mb-6"
      :class="preferencesStore.darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'"
    >
      <p class="text-sm" :class="preferencesStore.darkMode ? 'text-gray-400' : 'text-gray-600'" v-html="intro.text"></p>
      <p v-if="intro.source_note" class="text-sm mt-2" :class="preferencesStore.darkMode ? 'text-gray-400' : 'text-gray-600'">
        {{ intro.source_note }}
      </p>
    </div>

    <!-- Progress Summary -->
    <div
      class="p-6 rounded-lg border mb-6"
      :class="[
        preferencesStore.darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200',
        progress.allComplete
          ? (preferencesStore.darkMode ? 'border-green-700' : 'border-green-200')
          : ''
      ]"
    >
      <div class="flex items-center gap-6">
        <!-- Progress Ring -->
        <div class="relative w-24 h-24 flex-shrink-0">
          <svg class="w-full h-full transform -rotate-90">
            <circle
              cx="48"
              cy="48"
              r="40"
              stroke="currentColor"
              stroke-width="8"
              fill="none"
              :class="preferencesStore.darkMode ? 'text-gray-700' : 'text-gray-200'"
            />
            <circle
              cx="48"
              cy="48"
              r="40"
              :stroke="progress.allComplete
                ? (preferencesStore.darkMode ? '#10b981' : '#059669')
                : (preferencesStore.darkMode ? '#3b82f6' : '#2563eb')"
              stroke-width="8"
              fill="none"
              stroke-linecap="round"
              :stroke-dasharray="`${progress.percent * 2.51} 251`"
              class="transition-all duration-500"
            />
          </svg>
          <div class="absolute inset-0 flex flex-col items-center justify-center">
            <div
              class="text-2xl font-bold"
              :class="progress.allComplete
                ? (preferencesStore.darkMode ? 'text-green-400' : 'text-green-600')
                : (preferencesStore.darkMode ? 'text-blue-400' : 'text-blue-600')"
            >
              {{ progress.percent }}%
            </div>
            <div
              class="text-xs"
              :class="preferencesStore.darkMode ? 'text-gray-500' : 'text-gray-500'"
            >
              {{ progress.completed }}/{{ progress.total }}
            </div>
          </div>
        </div>

        <!-- Status Text -->
        <div class="flex-1">
          <h3
            class="text-lg font-semibold mb-1"
            :class="preferencesStore.darkMode ? 'text-white' : 'text-gray-900'"
          >
            {{ progress.allComplete ? 'Validation Complete' : 'Validation In Progress' }}
          </h3>
          <p
            class="text-sm"
            :class="preferencesStore.darkMode ? 'text-gray-400' : 'text-gray-600'"
          >
            {{ progress.allComplete
              ? 'All required items completed. Your AI is ready for clinical review.'
              : `${progress.total - progress.completed} required items remaining.`
            }}
          </p>

          <!-- Download button -->
          <button
            v-if="progress.completed > 0"
            @click="downloadValidationReport"
            class="mt-3 flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium transition-colors"
            :class="preferencesStore.darkMode
              ? 'bg-blue-600 text-white hover:bg-blue-500'
              : 'bg-blue-600 text-white hover:bg-blue-700'"
          >
            <Download class="w-4 h-4" />
            Export Validation Report
          </button>
        </div>
      </div>
    </div>

    <!-- Checklist Sections -->
    <div class="space-y-4">
      <div
        v-for="section in sections"
        :key="section.id"
        class="rounded-lg border overflow-hidden"
        :class="preferencesStore.darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'"
      >
        <!-- Section Header -->
        <button
          @click="toggleSection(section.id)"
          class="w-full px-4 py-3 flex items-center justify-between transition-colors"
          :class="preferencesStore.darkMode ? 'hover:bg-gray-700' : 'hover:bg-gray-50'"
        >
          <div class="flex items-center gap-3">
            <component
              :is="expandedSections.has(section.id) ? ChevronDown : ChevronUp"
              class="w-5 h-5"
              :class="preferencesStore.darkMode ? 'text-gray-500' : 'text-gray-400'"
            />
            <div class="text-left">
              <h3
                class="font-semibold"
                :class="preferencesStore.darkMode ? 'text-white' : 'text-gray-900'"
              >
                {{ section.title }}
              </h3>
              <p
                class="text-sm"
                :class="preferencesStore.darkMode ? 'text-gray-400' : 'text-gray-500'"
              >
                {{ section.description }}
              </p>
            </div>
          </div>

          <!-- Section Progress -->
          <div
            class="text-sm font-medium px-3 py-1 rounded-full"
            :class="getSectionProgress(section).percent === 100
              ? (preferencesStore.darkMode ? 'bg-green-900/50 text-green-300' : 'bg-green-100 text-green-700')
              : (preferencesStore.darkMode ? 'bg-gray-700 text-gray-300' : 'bg-gray-200 text-gray-700')"
          >
            {{ getSectionProgress(section).completed }}/{{ getSectionProgress(section).total }}
          </div>
        </button>

        <!-- Section Items -->
        <div
          v-if="expandedSections.has(section.id)"
          class="px-4 py-3 border-t space-y-3"
          :class="preferencesStore.darkMode ? 'border-gray-700 bg-gray-800/50' : 'border-gray-200 bg-gray-50'"
        >
          <div
            v-for="item in section.items"
            :key="item.id"
            class="p-3 rounded-lg"
            :class="preferencesStore.darkMode ? 'bg-gray-700' : 'bg-white'"
          >
            <label class="flex items-start gap-3 cursor-pointer group">
              <!-- Checkbox -->
              <div class="flex-shrink-0 mt-0.5">
                <input
                  type="checkbox"
                  :checked="checkedItems.has(item.id)"
                  @change="toggleItem(item.id)"
                  class="sr-only"
                />
                <component
                  :is="checkedItems.has(item.id) ? CheckCircle : Circle"
                  class="w-5 h-5 transition-colors"
                  :class="checkedItems.has(item.id)
                    ? 'text-green-500'
                    : (preferencesStore.darkMode
                        ? 'text-gray-600 group-hover:text-gray-500'
                        : 'text-gray-400 group-hover:text-gray-500')"
                />
              </div>

              <!-- Item Content -->
              <div class="flex-1 min-w-0">
                <div class="flex items-start justify-between gap-2">
                  <span
                    class="font-medium"
                    :class="[
                      preferencesStore.darkMode ? 'text-white' : 'text-gray-900',
                      checkedItems.has(item.id) ? 'line-through opacity-75' : ''
                    ]"
                  >
                    {{ item.text }}
                  </span>
                  <span
                    v-if="item.required"
                    class="flex-shrink-0 text-xs px-2 py-0.5 rounded-full font-medium"
                    :class="preferencesStore.darkMode
                      ? 'bg-red-900/50 text-red-300'
                      : 'bg-red-100 text-red-700'"
                  >
                    Required
                  </span>
                  <span
                    v-else
                    class="flex-shrink-0 text-xs px-2 py-0.5 rounded-full"
                    :class="preferencesStore.darkMode
                      ? 'bg-gray-600 text-gray-300'
                      : 'bg-gray-200 text-gray-600'"
                  >
                    Optional
                  </span>
                </div>

                <!-- Details -->
                <details
                  v-if="item.details"
                  class="mt-2"
                >
                  <summary
                    class="text-xs flex items-center gap-1 cursor-pointer"
                    :class="preferencesStore.darkMode ? 'text-blue-400 hover:text-blue-300' : 'text-blue-600 hover:text-blue-700'"
                  >
                    <Info class="w-3 h-3" />
                    Details
                  </summary>
                  <p
                    class="mt-2 text-sm whitespace-pre-wrap"
                    :class="preferencesStore.darkMode ? 'text-gray-400' : 'text-gray-600'"
                  >
                    {{ item.details }}
                  </p>
                </details>
              </div>
            </label>
          </div>
        </div>
      </div>
    </div>

    <!-- Completion Message -->
    <div
      v-if="progress.allComplete"
      class="mt-6 p-6 rounded-lg border-2"
      :class="preferencesStore.darkMode
        ? 'bg-green-900/30 border-green-700'
        : 'bg-green-50 border-green-200'"
    >
      <div class="flex items-start gap-4">
        <CheckCircle
          class="w-8 h-8 flex-shrink-0"
          :class="preferencesStore.darkMode ? 'text-green-400' : 'text-green-600'"
        />
        <div>
          <h3
            class="text-xl font-bold mb-2"
            :class="preferencesStore.darkMode ? 'text-green-300' : 'text-green-800'"
          >
            Validation Complete
          </h3>
          <p
            class="mb-3"
            :class="preferencesStore.darkMode ? 'text-green-400' : 'text-green-700'"
          >
            You've completed all required validation items. Your AI system is ready for:
          </p>
          <ul
            class="text-sm space-y-1"
            :class="preferencesStore.darkMode ? 'text-green-400' : 'text-green-700'"
          >
            <li>• Clinical deployment review by your institution</li>
            <li>• Publication in peer-reviewed medical journals</li>
            <li>• Regulatory submission (if pursuing FDA clearance)</li>
          </ul>

          <button
            @click="downloadValidationReport"
            class="mt-4 flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-colors"
            :class="preferencesStore.darkMode
              ? 'bg-green-600 text-white hover:bg-green-500'
              : 'bg-green-600 text-white hover:bg-green-700'"
          >
            <Download class="w-4 h-4" />
            Download Validation Report
          </button>
        </div>
      </div>
    </div>

    <!-- Disclaimer -->
    <div
      class="mt-6 p-4 rounded-lg border text-sm"
      :class="preferencesStore.darkMode
        ? 'bg-orange-900/20 border-orange-800 text-orange-400'
        : 'bg-orange-50 border-orange-200 text-orange-700'"
    >
      <p class="font-medium mb-1">Important Note:</p>
      <p>
        This checklist is a planning tool, not a substitute for formal validation documentation.
        Consult your institution's clinical deployment review board and regulatory affairs office
        for official requirements.
      </p>
    </div>
  </AppletFrame>
</template>
