<script setup>
import { ref, computed } from 'vue'
import { useAiGuidanceStore } from '../../stores/aiGuidanceStore'
import { useConfigStore } from '@/stores/configStore'
import { usePreferencesStore } from '@/stores/preferencesStore'
import AppletFrame from '../../components/AppletFrame.vue'
import DecisionFlow from '../../components/DecisionFlow.vue'
import NarrativeGuide from '../../components/clinical/NarrativeGuide.vue'
import {
  Users,
  CheckCircle,
  AlertTriangle,
  FileText,
  Download,
  Clock,
  ChevronDown,
  ChevronUp
} from 'lucide-vue-next'

const aiStore = useAiGuidanceStore()
const configStore = useConfigStore()
const preferencesStore = usePreferencesStore()

const APPLET_ID = 'clinical-irb-amendment'

// Load config from YAML
const appletConfig = computed(() => {
  return configStore.config?.clinicalGuidance?.['irb-amendment'] || {}
})

// Transform YAML to DecisionFlow format
const questions = computed(() => {
  const yamlQuestions = appletConfig.value.questions || []
  return yamlQuestions.map(q => ({
    id: q.id,
    question: q.question,
    helpText: q.help_text,
    learnMore: q.learn_more,
    options: (q.options || []).map(opt => ({
      value: opt.value,
      label: opt.label,
      description: opt.description,
      setsOutput: opt.sets_output || {},
      setsFlags: opt.sets_flags || [],
      next: opt.next
    }))
  }))
})

const outcomes = computed(() => appletConfig.value.outcomes || {})
const sampleLanguage = computed(() => appletConfig.value.sample_language || {})
const intro = computed(() => appletConfig.value.intro || {})

const result = ref(null)
const isComplete = computed(() => result.value !== null)

// Track which narrative sections are expanded
const expandedSections = ref(new Set())

function toggleSection(sectionName) {
  if (expandedSections.value.has(sectionName)) {
    expandedSections.value.delete(sectionName)
  } else {
    expandedSections.value.add(sectionName)
  }
}

function handleComplete({ output, flags }) {
  let outcome = 'no-amendment-needed'

  if (output.needs_amendment && output.amendment_type === 'full') {
    outcome = 'needs-full-amendment'
  } else if (output.needs_amendment) {
    outcome = 'needs-minor-amendment'
  }

  const outcomeData = outcomes.value[outcome] || {}

  result.value = {
    outcome,
    ...outcomeData,
    flags,
    output
  }

  aiStore.completeApplet(APPLET_ID, {
    outcome,
    needsAmendment: output.needs_amendment || false,
    amendmentType: output.amendment_type,
    flags
  })
}

function getNextApplet() {
  // After IRB amendment, suggest going to clinical validation
  return 'clinical-validation'
}

const iconMap = {
  'check-circle': CheckCircle,
  'alert-triangle': AlertTriangle
}

function getIcon(iconName) {
  return iconMap[iconName] || AlertTriangle
}

function getLevelColorClasses(color) {
  const isDark = preferencesStore.darkMode
  const colors = {
    green: isDark ? 'bg-green-900/30 border-green-700 text-green-400' : 'bg-green-50 border-green-200 text-green-700',
    yellow: isDark ? 'bg-yellow-900/30 border-yellow-700 text-yellow-400' : 'bg-yellow-50 border-yellow-200 text-yellow-700',
    orange: isDark ? 'bg-orange-900/30 border-orange-700 text-orange-400' : 'bg-orange-50 border-orange-200 text-orange-700'
  }
  return colors[color] || colors.yellow
}

// Download amendment draft
function downloadAmendmentDraft() {
  const protocol = sampleLanguage.value.protocol_amendment?.sections?.[0]?.content || ''
  const consent = sampleLanguage.value.consent_form_additions?.variants?.[1]?.content || ''
  const checklist = (sampleLanguage.value.submission_checklist?.items || []).join('\n- ')

  const draft = `# IRB Amendment Draft

## Protocol Amendment: Data Analysis Methods

${protocol}

---

## Consent Form Addition

${consent}

---

## Submission Checklist

- ${checklist}

---

*Generated by OpenDataPlanner Clinical AI Guidance on ${new Date().toLocaleDateString()}*
*This is a draft template. Customize for your study before submission.*
`

  const blob = new Blob([draft], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `irb-amendment-draft-${new Date().toISOString().slice(0, 10)}.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
</script>

<template>
  <AppletFrame
    :applet-id="APPLET_ID"
    :title="appletConfig.meta?.title || 'IRB Amendment Guide'"
    :core-question="appletConfig.meta?.core_question || 'Do I need to amend my IRB protocol?'"
    :icon="Users"
    :is-complete="isComplete"
    :get-next-applet="getNextApplet"
  >
    <!-- Intro -->
    <div
      v-if="intro.text"
      class="p-4 rounded-lg border mb-6"
      :class="preferencesStore.darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'"
    >
      <p class="text-sm" :class="preferencesStore.darkMode ? 'text-gray-400' : 'text-gray-600'" v-html="intro.text"></p>
      <p v-if="intro.source_note" class="text-sm mt-2" :class="preferencesStore.darkMode ? 'text-gray-400' : 'text-gray-600'">
        {{ intro.source_note }}
      </p>
    </div>

    <DecisionFlow :questions="questions" @complete="handleComplete">
      <template #complete="{ output, flags }">
        <!-- Decision Result -->
        <div class="p-6 rounded-lg border-2 mb-6" :class="getLevelColorClasses(result.color)">
          <div class="flex items-start gap-4">
            <component :is="getIcon(result.icon)" class="w-8 h-8 flex-shrink-0" />
            <div class="flex-1">
              <h3 class="text-xl font-bold mb-2" :class="preferencesStore.darkMode ? 'text-white' : 'text-gray-900'">
                {{ result.title }}
              </h3>
              <p class="mb-3">{{ result.description }}</p>

              <!-- Timeline -->
              <div v-if="result.timeline" class="flex items-center gap-2 mb-3 text-sm">
                <Clock class="w-4 h-4" />
                <span>{{ result.timeline }}</span>
              </div>

              <!-- Recommendations -->
              <div v-if="result.recommendations">
                <p class="text-sm font-medium mb-2">What to do:</p>
                <ul class="text-sm space-y-1">
                  <li v-for="(item, idx) in result.recommendations" :key="idx">
                    • {{ item }}
                  </li>
                </ul>
              </div>

              <!-- Next Steps -->
              <div v-if="result.next_steps" class="mt-4">
                <p class="text-sm font-medium mb-2">Next Steps:</p>
                <ol class="text-sm space-y-1">
                  <li v-for="(item, idx) in result.next_steps" :key="idx">
                    {{ idx + 1 }}. {{ item }}
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>

        <!-- Sample Language (shown when amendment needed) -->
        <div v-if="output.needs_amendment && sampleLanguage" class="space-y-4">
          <div class="flex items-center justify-between mb-4">
            <h3
              class="text-lg font-semibold"
              :class="preferencesStore.darkMode ? 'text-white' : 'text-gray-900'"
            >
              Sample Amendment Language
            </h3>
            <button
              @click="downloadAmendmentDraft"
              class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium transition-colors"
              :class="preferencesStore.darkMode
                ? 'bg-blue-600 text-white hover:bg-blue-500'
                : 'bg-blue-600 text-white hover:bg-blue-700'"
            >
              <Download class="w-4 h-4" />
              Download Draft
            </button>
          </div>

          <!-- Protocol Amendment -->
          <div
            class="rounded-lg border overflow-hidden"
            :class="preferencesStore.darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'"
          >
            <button
              @click="toggleSection('protocol')"
              class="w-full px-4 py-3 flex items-center justify-between"
              :class="preferencesStore.darkMode ? 'hover:bg-gray-700' : 'hover:bg-gray-50'"
            >
              <div class="flex items-center gap-2">
                <FileText class="w-5 h-5" />
                <span class="font-medium">{{ sampleLanguage.protocol_amendment?.title }}</span>
              </div>
              <component
                :is="expandedSections.has('protocol') ? ChevronUp : ChevronDown"
                class="w-5 h-5"
              />
            </button>
            <div
              v-if="expandedSections.has('protocol')"
              class="px-4 py-3 border-t"
              :class="preferencesStore.darkMode ? 'border-gray-700 bg-gray-800/50' : 'border-gray-200 bg-gray-50'"
            >
              <div
                v-for="section in sampleLanguage.protocol_amendment?.sections"
                :key="section.section"
                class="mb-4 last:mb-0"
              >
                <p class="text-sm font-medium mb-2" :class="preferencesStore.darkMode ? 'text-gray-300' : 'text-gray-700'">
                  {{ section.section }}
                </p>
                <pre
                  class="text-sm p-3 rounded bg-black/10 whitespace-pre-wrap font-mono"
                  :class="preferencesStore.darkMode ? 'text-gray-300' : 'text-gray-700'"
                >{{ section.content }}</pre>
              </div>
            </div>
          </div>

          <!-- Consent Form Additions -->
          <div
            class="rounded-lg border overflow-hidden"
            :class="preferencesStore.darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'"
          >
            <button
              @click="toggleSection('consent')"
              class="w-full px-4 py-3 flex items-center justify-between"
              :class="preferencesStore.darkMode ? 'hover:bg-gray-700' : 'hover:bg-gray-50'"
            >
              <div class="flex items-center gap-2">
                <FileText class="w-5 h-5" />
                <span class="font-medium">{{ sampleLanguage.consent_form_additions?.title }}</span>
              </div>
              <component
                :is="expandedSections.has('consent') ? ChevronUp : ChevronDown"
                class="w-5 h-5"
              />
            </button>
            <div
              v-if="expandedSections.has('consent')"
              class="px-4 py-3 border-t space-y-4"
              :class="preferencesStore.darkMode ? 'border-gray-700 bg-gray-800/50' : 'border-gray-200 bg-gray-50'"
            >
              <div
                v-for="variant in sampleLanguage.consent_form_additions?.variants"
                :key="variant.name"
                class="p-3 rounded-lg"
                :class="preferencesStore.darkMode ? 'bg-gray-700' : 'bg-white border border-gray-200'"
              >
                <p class="text-sm font-medium mb-1" :class="preferencesStore.darkMode ? 'text-white' : 'text-gray-900'">
                  {{ variant.name }}
                </p>
                <p class="text-xs mb-2" :class="preferencesStore.darkMode ? 'text-gray-400' : 'text-gray-500'">
                  Use when: {{ variant.use_when }}
                </p>
                <pre
                  class="text-sm p-3 rounded bg-black/10 whitespace-pre-wrap font-mono"
                  :class="preferencesStore.darkMode ? 'text-gray-300' : 'text-gray-700'"
                >{{ variant.content }}</pre>
              </div>
            </div>
          </div>

          <!-- Submission Checklist -->
          <div
            class="rounded-lg border overflow-hidden"
            :class="preferencesStore.darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'"
          >
            <button
              @click="toggleSection('checklist')"
              class="w-full px-4 py-3 flex items-center justify-between"
              :class="preferencesStore.darkMode ? 'hover:bg-gray-700' : 'hover:bg-gray-50'"
            >
              <div class="flex items-center gap-2">
                <CheckCircle class="w-5 h-5" />
                <span class="font-medium">{{ sampleLanguage.submission_checklist?.title }}</span>
              </div>
              <component
                :is="expandedSections.has('checklist') ? ChevronUp : ChevronDown"
                class="w-5 h-5"
              />
            </button>
            <div
              v-if="expandedSections.has('checklist')"
              class="px-4 py-3 border-t"
              :class="preferencesStore.darkMode ? 'border-gray-700 bg-gray-800/50' : 'border-gray-200 bg-gray-50'"
            >
              <ul class="space-y-2 text-sm" :class="preferencesStore.darkMode ? 'text-gray-300' : 'text-gray-700'">
                <li v-for="(item, idx) in sampleLanguage.submission_checklist?.items" :key="idx">
                  {{ item }}
                </li>
              </ul>

              <div
                v-if="sampleLanguage.submission_checklist?.expected_timelines"
                class="mt-4 pt-4 border-t"
                :class="preferencesStore.darkMode ? 'border-gray-600' : 'border-gray-300'"
              >
                <p class="text-sm font-medium mb-2">Expected Timelines:</p>
                <ul class="text-sm space-y-1" :class="preferencesStore.darkMode ? 'text-gray-400' : 'text-gray-600'">
                  <li v-for="(timeline, idx) in sampleLanguage.submission_checklist.expected_timelines" :key="idx">
                    • {{ timeline }}
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Institutional Resources -->
        <div
          v-if="appletConfig.institutional"
          class="mt-6 p-4 rounded-lg border text-sm"
          :class="preferencesStore.darkMode
            ? 'bg-gray-800 border-gray-700'
            : 'bg-gray-100 border-gray-200'"
        >
          <p class="font-medium mb-2" :class="preferencesStore.darkMode ? 'text-gray-300' : 'text-gray-700'">
            Your IRB Resources:
          </p>
          <ul class="space-y-1" :class="preferencesStore.darkMode ? 'text-gray-400' : 'text-gray-600'">
            <li v-if="appletConfig.institutional.irb_portal_url">
              IRB Portal:
              <a
                :href="appletConfig.institutional.irb_portal_url"
                target="_blank"
                rel="noopener noreferrer"
                class="hover:underline ml-1"
                :class="preferencesStore.darkMode ? 'text-blue-400' : 'text-blue-600'"
              >
                {{ appletConfig.institutional.irb_portal_url }}
              </a>
            </li>
            <li v-if="appletConfig.institutional.irb_office_contact">
              Contact: {{ appletConfig.institutional.irb_office_contact }}
            </li>
          </ul>
        </div>
      </template>
    </DecisionFlow>
  </AppletFrame>
</template>
