// Persona-session harness — the runner's shared, side-effect-light core.
//
// This is the code half of docs/ux/PLAYWRIGHT-PERSONA-SESSIONS.md (Piper's spec).
// It loads a session brief, resolves its persona + target URL, and assembles the
// artifacts a recorded think-aloud run produces: the agent's session packet, the
// narration log, and the verdict scaffold. Pure helpers live here (no Playwright
// import) so the vitest unit suite can exercise them; the browser plumbing that
// records video + trace lives in session.spec.mjs and persona-session.mjs.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import yaml from 'js-yaml'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
export const REPO_ROOT = path.resolve(__dirname, '..', '..')

export const SESSIONS_DIR = path.join(REPO_ROOT, 'docs', 'ux', 'sessions')
export const PERSONAS_DIR = path.join(REPO_ROOT, 'docs', 'ux', 'personas')
export const REVIEWS_DIR = path.join(REPO_ROOT, 'docs', 'ux', 'reviews', 'playwright')

// staging and dev are the same address — xram's Northwinds copy, the one the
// incorporeal faculty would actually touch (spec PLAYWRIGHT-PERSONA-SESSIONS.md).
// local points at the Vite dev server for branch testing.
export const TARGETS = {
  staging: 'https://openresearchdataplanner.dev.xram.net',
  dev: 'https://openresearchdataplanner.dev.xram.net',
  local: 'http://localhost:5173',
}

const REQUIRED_BRIEF_FIELDS = ['session_id', 'persona', 'goal', 'success_criteria']

// Load + validate a session brief. Throws with an actionable message rather than
// letting a half-formed brief produce a silently-broken run.
export function loadBrief(sessionId) {
  const file = path.join(SESSIONS_DIR, `${sessionId}.yaml`)
  if (!fs.existsSync(file)) {
    throw new Error(`No session brief at ${path.relative(REPO_ROOT, file)} — check the session_id.`)
  }
  const brief = yaml.load(fs.readFileSync(file, 'utf8'))

  const missing = REQUIRED_BRIEF_FIELDS.filter((f) => brief[f] == null || brief[f] === '')
  if (missing.length) {
    throw new Error(`Brief ${sessionId} is missing required field(s): ${missing.join(', ')}`)
  }
  if (brief.session_id !== sessionId) {
    throw new Error(`Brief session_id "${brief.session_id}" does not match filename "${sessionId}".`)
  }
  if (!Array.isArray(brief.success_criteria) || brief.success_criteria.length === 0) {
    throw new Error(`Brief ${sessionId} has no success_criteria — there is nothing to verify.`)
  }

  const personaDir = path.join(PERSONAS_DIR, brief.persona)
  if (!fs.existsSync(personaDir)) {
    throw new Error(
      `Brief ${sessionId} references persona "${brief.persona}" but ${path.relative(REPO_ROOT, personaDir)} does not exist.`,
    )
  }
  return { brief, personaDir }
}

// Resolve where a session points. Explicit --url wins; otherwise map the brief's
// target (or a CLI override) through TARGETS.
export function resolveTarget(target, urlOverride) {
  if (urlOverride) return urlOverride.replace(/\/$/, '')
  const key = target || 'staging'
  const url = TARGETS[key]
  if (!url) {
    throw new Error(`Unknown target "${key}" — known targets: ${Object.keys(TARGETS).join(', ')}.`)
  }
  return url
}

export function sessionDir(sessionId) {
  return path.join(REVIEWS_DIR, sessionId)
}

// Read the persona's definition so we can fold it into the session packet. The
// persona folder owns the identity; we never redefine it here, we quote it.
export function readPersona(personaDir) {
  const candidates = ['persona.md', 'README.md', `${path.basename(personaDir)}.md`]
  for (const name of candidates) {
    const p = path.join(personaDir, name)
    if (fs.existsSync(p)) return fs.readFileSync(p, 'utf8')
  }
  // Fall back to the first markdown file in the folder.
  const md = fs.readdirSync(personaDir).find((f) => f.endsWith('.md'))
  if (md) return fs.readFileSync(path.join(personaDir, md), 'utf8')
  throw new Error(`No markdown persona definition found in ${path.relative(REPO_ROOT, personaDir)}.`)
}

// The session packet is the prompt handed to the agent embodying the persona.
// It carries identity + goal + how to narrate + how to cite stalls, so a run is
// fully reproducible from one file in the review folder.
export function buildSessionPacket(brief, { url, personaText }) {
  const criteria = brief.success_criteria.map((c, i) => `${i + 1}. ${c}`).join('\n')
  return `# Session packet — ${brief.session_id}

> Generated by the persona-session runner. This is the brief the agent loads to
> drive the live app as the persona and narrate think-aloud. Do not edit by hand.

**Target:** ${url}
**Start at:** ${url}${brief.start_url || '/'}
**Persona folder:** docs/ux/personas/${brief.persona}
**Narration protocol:** ${brief.narration_protocol || 'think-aloud'}

## You are this persona

${personaText.trim()}

## Your goal for this session

${brief.goal.trim()}

## What counts as success

You do not get told these in advance inside the app — they are how we score the
run afterward. Pursue your goal naturally; we check these against what happened.

${criteria}

## How to narrate (think-aloud)

- Before each action, say **what you are looking for and what you expect**.
- After each action, say **whether the app met that expectation**.
- **Confusion is the data.** When something is ambiguous, dead-ends, or surprises
  you, narrate it — do not silently resolve it. "I don't see where to enter dates…
  oh, they're hidden until I pick a period" is a finding in one sentence.
- Stay in character. React the way this faculty member would, not the way a
  patient tester would.

## Citing where you got stuck

The app makes stall points addressable — use them so every finding is a link:

- The tier questionnaire reflects the current node to the URL hash as \`#q-<id>\`.
  When you stall on a question, record the full URL (e.g.
  \`${url}/tier-check#q-phi_identifiable\`).
- Each question has an **"I don't understand this!"** help button that emits a
  copy-paste support string (link + question text + path so far + tier/flags). If
  you reach for it, note which \`#q-<id>\` node drove you to it — that is exactly the
  signal we want.
- The wizard route is \`/\`; the standalone tier questionnaire is \`/tier-check\`;
  calculators \`/calculators\`; services \`/services\`; software \`/software\`.

## What the run produces

- \`video.webm\` — the whole session.
- \`trace.zip\` — Playwright trace (open with \`npx playwright show-trace\`).
- \`narration.md\` — your timestamped think-aloud, interleaved with the action
  that triggered each line. This is the gold.
- \`verdict.md\` — scored after the run against the success criteria above.
`
}

export function narrationHeader(brief, url) {
  return `# Narration — ${brief.session_id}

> Timestamped think-aloud transcript. Each entry: \`[mm:ss] (intent|observe|stall) — line\`,
> with the action that triggered it. Stalls cite a \`#q-<id>\` node or route when one applies.

- **Persona:** ${brief.persona}
- **Target:** ${url}
- **Protocol:** ${brief.narration_protocol || 'think-aloud'}

---

`
}

// Verdict scaffold. Piper owns the verdict *schema*; this is just the plumbing
// that pre-fills the success criteria so triage starts from a consistent shape.
export function verdictScaffold(brief) {
  const criteria = brief.success_criteria
    .map((c) => `- [ ] ${c}\n      - Result: \n      - Evidence (timestamp / #q-<id> / route): `)
    .join('\n')
  return `# Verdict — ${brief.session_id}

> Scored after the run. Schema owned by @piper (PLAYWRIGHT-PERSONA-SESSIONS.md).
> The runner pre-fills the success criteria; a human/agent fills the rest.

**Persona:** ${brief.persona}
**Run:** _date / commit_

## Success criteria

${criteria}

## Where they stalled

| # | Node / route | What confused them | Severity |
|---|--------------|--------------------|----------|
|   |              |                    |          |

## Top 3 friction moments (ranked)

1.
2.
3.

## One-line summary

`
}

// Slugify a millisecond offset into mm:ss for narration timestamps.
export function stamp(ms) {
  const total = Math.max(0, Math.round(ms / 1000))
  const m = String(Math.floor(total / 60)).padStart(2, '0')
  const s = String(total % 60).padStart(2, '0')
  return `${m}:${s}`
}
